ServerEvents.recipes(event => {

event.recipes.create.milling( [Item.of('crusty_chunks:lead_dust').withChance(0.25), 'crusty_chunks:lead_dust'], '#forge:raw_materials/lead')
event.recipes.create.milling( [Item.of('crusty_chunks:iron_dust').withChance(0.25), 'crusty_chunks:iron_dust'], '#forge:raw_materials/iron')
event.recipes.create.milling( [Item.of('crusty_chunks:gold_dust').withChance(0.25), 'crusty_chunks:gold_dust'], '#forge:raw_materials/gold')
event.recipes.create.milling( [Item.of('crusty_chunks:copper_dust').withChance(0.25), 'crusty_chunks:copper_dust'], '#forge:raw_materials/copper')
event.recipes.create.milling( [Item.of('crusty_chunks:zinc_dust').withChance(0.25), 'crusty_chunks:zinc_dust'], '#forge:raw_materials/zinc')
event.recipes.create.milling( [Item.of('crusty_chunks:nickel_dust').withChance(0.25), 'crusty_chunks:nickel_dust'], '#forge:raw_materials/nickel')
event.recipes.create.milling( [Item.of('crusty_chunks:bauxite_dust').withChance(0.25), 'crusty_chunks:bauxite_dust'], 'crusty_chunks:bauxite')
event.recipes.create.milling( [Item.of('crusty_chunks:uranium_neutraltiny_dust').withChance(0.25), 'crusty_chunks:uranium_neutraltiny_dust'], '#forge:raw_materials/uranium')
event.recipes.create.milling( [Item.of('crusty_chunks:uranium_enriched_tiny_dust').withChance(0.25), 'crusty_chunks:uranium_enriched_tiny_dust'], '#forge:raw_materials/uranium')
event.recipes.create.milling( [Item.of('crusty_chunks:uranium_depleted_tiny_dust').withChance(0.25), 'crusty_chunks:uranium_depleted_tiny_dust'], '#forge:raw_materials/uranium')
event.recipes.create.milling( [Item.of('crusty_chunks:beryllium_dust').withChance(0.25), 'crusty_chunks:beryllium_dust'], '#forge:raw_materials/beryllium')
event.recipes.create.milling( [Item.of('crusty_chunks:lithium_dust').withChance(0.25), 'crusty_chunks:lithium_dust'], '#forge:raw_materials/lithium')
})